config: ''
# Fit options configuration

fit_options:

  stat_opt: 20years # time period for sensitivity studies
  sin2_th13_opt: free   # Sin2_theta13 option
  osc_formula_opt: default # Oscillation formula option, default is PDG, YB is yellowbook
  PDG_opt: PDG2019 # PDG option
  NMO_opt: true   # NMO option, true is normal
  min_ene: 0.8  # Minimum energy
  max_ene: 9.0 # Maximum energy
  bins: 411 # Number of bins
  stat_method_opt: CNP #NorP, CNP, or bayesian
  grid_scan: false # if not grid scan, iminuit is run
  plot_minuit_matrix: false
  plot_minuit_profiles: false
  print_minuit_correlation: false
  #just for the bayesian method, random seeds and chi2 def
  bayes_seed_beg: 481
  bayes_chi2: CNP
  bayes_events: 400
  bayes_nwalkers: 30
  bayes_nprocesses: 16
  # Energy crop range for fit
  ene_crop:
    - 0.8
    - 9.0

  # Energy crop range for nevents calculation
  ene_crop2:
    - 0.8
    - 12.0

  FORCE_CALC_RM: false # Force calculation of response matrix
  FORCE_CALC_CM: false # Force calculation of covariance matrices
  PLOT_CM: false # Plot covariance matrices


  input_data_file: ../../noda_diana_version/noda/2020/Data/JUNOInputs2022_05_08.root #data file
  reactor_model: Huber-Mueller

  main_data_folder: ../Data_test
  cov_matrix_plots_folder: ../Data_test/CMplots #folder to store CM plots
  plots_folder: ../Data_test/Plots #folder to save plots of spectra
  data_matrix_folder: ../Data_test #folder to save or to use csv files of spectra and matrices
  bayes_data_folder: ../Data_test/Bayesian/npz_files
  bayes_plots_folder: ../Data_test/Bayesian/Plots

  #start and end points for each parameter in grid space
  grid_params:
    sin2_12: [0.302, 0.312]
    sin2_13: [0.0068, 0.0368]
    dm2_21: [7.47e-5, 7.59e-5]
    dm2_31: [2.515e-3, 2.543e-3]

  #number of points for each parameter in the grid space
  grid_points: 21

  # Uncertainty list
  unc_list:
    - stat
    - stat+eff
    - stat+r2
    - stat+crel
    - stat+snf
    - stat+noneq
    - stat+b2b_DYB
    - stat+abc
    - stat+nl
    - stat+bg
    - stat+me
    - stat+eff+r2+crel+snf+noneq+b2b_DYB+abc+nl+bg+me

  bayes_unc: stat+eff+r2+crel+snf+noneq+b2b_DYB+abc+nl+bg+me

  sample_size_resp: 10000 # Sample size for response matrix fluctuations
  sample_size_core: 10000 # Sample size for core powers fluctuations
  sample_size_nonl: 10000 # Sample size for non-linearity fluctuations
  sample_size_me: 10000 # Sample size for matter effect fluctuations


# Juno Inputs
juno_inputs:
  core_baselines_1: [52760.0]
  core_powers_1: [4.6]
  core_powers_12: [2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 4.6, 4.6, 17.4, 17.4]
  core_baselines_12: [52750.0, 52840.0, 52420.0, 52510.0, 52120.0, 52210.0, 52760.0, 52630.0, 52320.0, 52200.0, 215000.0, 265000.0]
  core_powers_10: [2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 4.6, 4.6, 17.4, 17.4]
  core_baselines_10: [52750.0, 52840.0, 52420.0, 52510.0, 52120.0, 52210.0, 52760.0, 52630.0, 215000.0, 265000.0]
  core_powers_9: [2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 4.6, 4.6, 17.4]
  core_baselines_9: [52740.0, 52820.0, 52410.0, 52490.0, 52110.0, 52190.0, 52770.0, 52640.0, 215000.0]
  alpha: [0.58, 0.07, 0.30, 0.05]
  efission: [202.36, 205.99, 211.12, 214.26]
  Pth: [1.5634944e+27, 1.5634944e+27, 1.5634944e+27, 1.5634944e+27, 1.5634944e+27, 1.5634944e+27, 2.4800256e+27, 2.4800256e+27, 9.3809664e+27] # MeV per day
  L: [5275000.0, 5284000.0, 5242000.0, 5251000.0, 5212000.0, 5221000.0, 5276000.0, 5263000.0, 21500000.0] # Already in cm
  Np: 1.4351802862903064e+33
  detector_efficiency: 0.82
  me_rho: 2.45
  me_rho_scale: 0.15



  U235_scale: 0.58
  U238_scale: 0.07
  Pu239_scale: 0.30
  Pu241_scale: 0.05
  a: 0.0261
  b: 0.0082
  c: 0.0123
  a_err: 0.0002
  b_err: 0.0001
  c_err: 0.0004

  r2_unc: 0.02
  eff_unc: 0.01
  b2b_unc: 0.0134
  snf_unc: 0.3
  noneq_unc: 0.3
  core_flux_unc: 0.008
  acc_rate_unc: 0.01
  geo_rate_unc: 0.3
  geo_b2b_unc: 0.05
  lihe_rate_unc: 0.2
  lihe_b2b_unc: 0.1
  fneu_rate_unc: 1.0
  fneu_b2b_unc: 0.2
  aneu_rate_unc: 0.5
  aneu_b2b_unc: 0.5
  atm_rate_unc: 0.5
  atm_b2b_unc: 0.5
  rea300_rate_unc: 0.02
  rea300_b2b_unc: 0.05
